### ISSUE TITLE
Closing browser window and opening it again shows log in in upper bar

### ISSUE THREAD

**Issue by siom79** [rodrigokamada/angular-amazon-cognito#1]
Hi,

thank you for the great tutorial and example application. It really helped me figuring things out.

But I noticed that if you have successfully logged in and then close the browser window and open it again for the URL `http://localhost:4200/profile` it will show the Profile page. Which is OK as the Cognito Cookies are stored and your are authenticated, but you see the log in and log out links on the upper bar.

**Comment by rodrigokamada** [comment]
Hi @siom79!

I made a code improvement. See this [commit](https://github.com/rodrigokamada/angular-amazon-cognito/commit/e4c035f4974efb5a835a623de8beff3237fefbb6).

**Comment by siom79** [comment]
Great, thanks a lot.
